### ISSUE TITLE
Don't show empty home page

### ISSUE THREAD

**Issue by AlphaGit** [rochimensi/MSImages#63]
I'd suggest either removing the home page, so that you arrive directly to the image list, or that you provide some primary options for the user to do some other things.

I personally prefer removing the home page -- it seems to me that the users would be able to do most of their activities from the image listing.

![image](https://cloud.githubusercontent.com/assets/1113433/7035709/3d4a626a-dd51-11e4-8d43-9010cde1fddc.png)

**Comment by csenoseain** [comment]
I agree with removing the home page. I fixed it
